### ISSUE TITLE
Allow for selected cells to be parsed as markdown

### ISSUE THREAD

**Issue by hughjonesd** [atusy/ftExtra#10]
I'm the developer of [huxtable](https://github.com/hughjonesd/huxtable). I'd like to add support for markdown output to Word/Powerpoint via flextable, and @davidgohel pointed me to your package. Would it be possible to allow by-cell parsing as markdown, rather than only by-column? This would be great for me.

**Comment by atusy** [comment]
Currently this is not possible. But I will consider about it so to improve the consistency with `flextable`'s API. Thanks!

**Comment by atusy** [comment]
Oops, `colformat_md` is already consistent with `flextable`'s `colformat_*` functions.
They are designed to be work on selected columns.
In order to achieve your request, we need to add something line `as_md_paragraph` and let it work within `compose` function.

**Comment by atusy** [comment]
Your request should work fine now, @hughjonesd.

```r
library(flextable)
library(ftExtra
ft <- flextable(data.frame(x = c('**foo**', '**bar**')))
ft <- compose(ft, j = "x", i = 2, value = parse_md(x))
autofit(ft)
```

**Comment by atusy** [comment]
hmmm... there's an error with R CMD CHECKS on some environments.
https://github.com/atusy/ftExtra/runs/887907060?check_suite_focus=true#step:10:88

**Comment by atusy** [comment]
@hughjonesd 

I decided to change implementation so that parsing works within `as_paragraph`.
This is more consistent with the typical usage of  `flextable::compose` .

```r
library(flextable)
ft <- flextable(data.frame(
   x = c('**foo**', '**bar**'),
   stringsAsFactors = FALSE
))
ft <- compose(ft, j = "x", i = 2, value = as_paragraph(as_chunk_md(x)))
autofit(ft)
```

**Comment by hughjonesd** [comment]
Thank you! I'll modify huxtable to use this.

**Comment by hughjonesd** [comment]
Do you know roughly when this is expected on CRAN?

**Comment by hughjonesd** [comment]
Do you know roughly when this is expected on CRAN?

**Comment by atusy** [comment]
@hughjonesd 
Well, give me a moment.
I want to update some documents, but  am being lazy...
I'll try to submit by the end of this month.

**Comment by hughjonesd** [comment]
Ace!
