### ISSUE TITLE
colformat_md() not working with flextable version 0.9.5

### ISSUE THREAD

**Issue by sjr267** [atusy/ftExtra#100]
R version 4.3.3, ftExtra version 0.6.2. The example code from the README for parsing markdown texts using colformat_md() runs as expected when flextable version 0.9.4 is installed, but doesn't when flextable version 0.9.5 is installed. The resulting table made with flextable 0.9.5 shows all of the markdown syntax, rather than converting it to formatted text. I've reproduced this on 2 systems.

**Comment by atusy** [comment]
Thank you for the report. I reproduced the issue...
Give me sometime to investigate it.

**Comment by atusy** [comment]
It seems the bug comes from the internal change of flextable's data structure.
I made #101 to fix it.

@sjr267 Would give a try with `pak::pak("atusy/ftExtra#101)"`?

**Comment by sjr267** [comment]
Yes, that version works with flextable 0.9.5.
