### ISSUE TITLE
as_chunk_md fails when markdown contains multiple elements

### ISSUE THREAD

**Issue by hughjonesd** [atusy/ftExtra#14]
With recent master:

```
ft <- flextable(mtcars[1:2, 1:2])
ft <- compose(ft, i = 1, j = 1, value = as_paragraph(as_chunk_md("*italic* plain **bold**")))
## Error in x$data[i, j] <- value : 
##  number of items to replace is not a multiple of replacement length
```

**Comment by atusy** [comment]
It seems chunk has to be an 1-row `data.frame`.
However, markdown text with different decorations have to be separated into rows.
Am I right, @davidgohel ?

I think there are two things I can do.

1. Let `as_chunk_md` warn or stop when it finds multiple decorations, and recommend the following alternative.
2. Add `as_paragraph_md` which returns the `"paragraph"` object.

What do you think?

**Comment by hughjonesd** [comment]
Yes, I think `as_paragraph_md()` is natural, it can split the text into the appropriate chunks. And the point of markdown is to express different styles within text, so `as_chunk_md()` may be more granular than is needed.

**Comment by atusy** [comment]
@hughjonesd Thanks. I'll add `as_paragraph_md` and remove `as_chunk_md` in #15.

**Comment by davidgohel** [comment]
(Sorry, I was not able to answer before)

> [...] However, markdown text with different decorations have to be separated into rows. Am I right [...]

Yes, you are right. Text are stored with their decoration:

```
> as_chunk("ftExtra")
      txt font.size italic bold underlined color shading.color font.family vertical.align width height  url img_data
1 ftExtra        NA     NA   NA         NA  <NA>          <NA>        <NA>           <NA>    NA     NA <NA>     NULL
```

**Comment by atusy** [comment]
@davidgohel Don't worry. Big thanks for the explanation!
