### ISSUE TITLE
md uses ~ for subscript, commonmark uses it for strikethrough

### ISSUE THREAD

**Issue by hughjonesd** [atusy/ftExtra#16]
The `commonmark` extension “strikethrough” uses “~foo~” to mean foo with strikethrough styling. `ftExtra` uses it for subscript. This might cause compatibility problems. (I’m not saying who is right!)

**Comment by hughjonesd** [comment]
… and indeed github uses it for strikethrough. Sorry, I meant to write `~foo~`.

**Comment by atusy** [comment]
Yes. There is no right answer.
I personally prefer Pandoc's Markdown in terms of consistency with R Markdown.
You can optionally change the flavor by specifying `.from` argument (e.g., `colformat_md(.from = 'commonmark')`)

BTW, As far as I know, gfm has strikethrough but commonmark does not (<https://spec.commonmark.org/0.29/>).
Also, gfm spec originally requires double tildes (`~~`) for strikethrough (<https://github.github.com/gfm/#strikethrough-extension->), which is consistent with Pandoc's Markdown (<https://pandoc.org/MANUAL.html#Strikeout>).
I guess single tilde is a sort of shortcut.

**Comment by atusy** [comment]
Closing the issue because I prefer the current implementation.
