### ISSUE TITLE
Thematic breaks break as_paragraph_md

### ISSUE THREAD

**Issue by hughjonesd** [atusy/ftExtra#19]
Here's a MWE. The four lines should make a "thematic break" - a horizontal rule in HTML. Using latest master.

```
library(flextable)
ft <- flextable(
  data.frame(
    x = c('Thematic break\n\n----\n'),
    stringsAsFactors = FALSE
  )
)
ft <- compose(ft, j = "x", i = 1, value = ftExtra::as_paragraph_md(x))
## Error: Column 5 must be named.

```

**Comment by atusy** [comment]
Does flextable support horizontal rules?
ftExtra may support what flextable and Pandoc support.

BTW, ftExtra does not currently support line breaks...

``` r
names(flextable::as_chunk('foo'))[-1L]
#>  [1] "font.size"      "italic"         "bold"           "underlined"    
#>  [5] "color"          "shading.color"  "font.family"    "vertical.align"
#>  [9] "width"          "height"         "url"            "img_data"
```

<sup>Created on 2020-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by atusy** [comment]
Line breaks are now supported.
Yet, I have no plans to support horizontal rules.
I decided to `stop()` if markdown text contains multiple paragraphs or block elements other than the paragraph.
