### ISSUE TITLE
Error on travis

### ISSUE THREAD

**Issue by hughjonesd** [atusy/ftExtra#34]
Hi,

During a travis check I got the following error in a test:

/home/travis/R/Library/ftExtra/lua/math.lua:18: attempt to index a nil value (field 'system')

Details here:
https://travis-ci.org/github/hughjonesd/huxtable/jobs/744872506

The relevant test is here:
https://github.com/hughjonesd/huxtable/blob/master/tests/testthat/test-markdown.R
at line 39, where I convert a markdown-enabled huxtable using as_flextable.

I don't get the same error on my home machine.

**Comment by atusy** [comment]
It seems like `pandoc.system` module is available since 2.7.3.
https://pandoc.org/releases.html#pandoc-2.7.3-2019-06-11

Maybe I should check Pandoc version more strictly at here:
https://github.com/atusy/ftExtra/blob/f19c45548d3a24712ea68379d1a8a4ee1fda5821/R/as-paragraph-md.R#L42

**Comment by atusy** [comment]
Thanks for the report. It should be fixed.
