### ISSUE TITLE
Working with new line operators

### ISSUE THREAD

**Issue by DragonflyStats** [atusy/ftExtra#39]
Hi Atusy

I am wondering if you can suggest something that would solve the problem caused by the "\n" and "\n\n" characters here

```{r}
library(magrittr)

  thisText = c(
    "The Species are: \n \u2022The Eurasian otter (Lutra lutra)",
    "The Species are: \n \u2022The yellow-winged darter (Sympetrum flaveolum) \n \u2022 The common bottlenose dolphin (Tursiops truncatus) \n\n Additional Text Here"
  )


thisDF <- data.frame(
  thisGroup = c(1,2) ,
  thisText 
)

Scientific_Name <- c("Lutra lutra","Sympetrum flaveolum","Tursiops truncatus","Anser Anser")

thisDF_Flex <- thisDF %>%
  dplyr::mutate(dplyr::across(
    where(is.character),
    stringr::str_replace_all,
    setNames(paste0('*', Scientific_Name, '*'), Scientific_Name)
  )) %>%
  flextable::flextable() %>%
  width(width=c(1.5,9)) %>%
  align( align = "left", part = "all" ) %>%
  font(fontname = "Calibri",part="all") %>%
  fontsize(size = 12, part = "body")

thisDF_Flex %>%
  ftExtra::colformat_md()

```

The issue crops up at the end.  {ftExtra} does not allow multiple paragraphs in the first instance.  I note a different issue related to multiple paragraphs, but could not follow the contibutions.
Any help would be greatly appreciated.

**Comment by atusy** [comment]
**ftExtra** does not support multiple paragraphs because **flextable** does not.
It is still possible to insert line breaks.
Try https://ftextra.atusy.net/articles/format_columns.html#line-breaks-1

**Comment by atusy** [comment]
@DragonflyStats Does my comment answer you?

**Comment by DragonflyStats** [comment]
Yes it does.
The solution we used actually involved creating a different cell for each paragraph, but decorating the borders to make them appear as a single cell. I will write up a demonstration when I get a chance.

**Comment by atusy** [comment]
Great. I close this issue now, but feel free to add your demonstration and/or re-open if needed.
