### ISSUE TITLE
function chunk_dataframe

### ISSUE THREAD

**Issue by davidgohel** [atusy/ftExtra#49]
Hello 

I am now exporting `chunk_dataframe` 
https://github.com/davidgohel/flextable/blob/master/R/05_content.R#L60

This could help to avoid duplicating chunk structure here:
https://github.com/atusy/ftExtra/blob/master/R/as-paragraph-md.R#L106

So you would depend on a supported function. If you are OK, I can do a PR next week (I will send flextable new version on CRAN today).

KR,
David

**Comment by atusy** [comment]
Hi David,

Thank you for the suggestion. Yes, PR would be very helpful!!
