### ISSUE TITLE
Footnote support for flextable with more than 1 rows

### ISSUE THREAD

**Issue by 942kid** [atusy/ftExtra#55]
Hi,

First of all, thank you for the great package! 

I was playing around with the examples in the vignettes, and found that the footnote support seemed not working as expected if _more than 1 rows_ present in the flextable. Please see the example below adapted from the code in the package [vignette](https://ftextra.atusy.net/articles/format_columns.html#footnotes-1). 

``` r
library(flextable)
library(ftExtra)
data.frame(
  package = c("flextable", "ftExtra"),
  description = c("Original Flextable", "Extensions for 'Flextable'^[Supports of footnotes]"),
  stringsAsFactors = FALSE
) %>%
  as_flextable() %>%
  colformat_md() %>%
  flextable::autofit(add_w = 0.5)
#> Error in FUN(newX[, i], ...): Item 2 has 14 columns, inconsistent with item 1 which has 17 columns. To fill missing columns use fill=TRUE.
```

<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by atusy** [comment]
Thank you for using **ftExtra**.
I reproduced the issue with the CRAN version, but not on GitHub.
Maybe there a bug in CRAN version, which I fixed without being aware of it.
Would you try install the latest version on GitHub with

```
# Enable this universe
options(repos = c(
    atusy = 'https://atusy.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('ftExtra')
```

**Comment by 942kid** [comment]
Installing the GitHub version resolved the issue. Thanks for looking into the differences!

**Comment by atusy** [comment]
Great!
