### ISSUE TITLE
Error in ‘rmarkdown::pandoc_exec()’

### ISSUE THREAD

**Issue by JiaxiangBU** [atusy/ftExtra#6]
``` r
knitr::opts_chunk$set(warning = FALSE, message = FALSE, error = TRUE)
```

``` r
# remotes::install_github("atusy/ftExtra")
library(ftExtra)
```

``` r
data.frame(
  x = c("**bold**", "*italic*"),
  y = c("^superscript^", "~subscript~"),
  z = c("***~ft~^Extra^** is*", "*Cool*"),
  stringsAsFactors = FALSE
) %>%
  as_flextable() %>%
  colformat_md()
```

    ## Error in system(paste(rmarkdown::pandoc_exec(), tf, "--from", .from, "--to json"), : 'C:/Program' not found

I get this error when I run the example in the README.

**Comment by atusy** [comment]
Thank you for the report. Let me see what you get with `rmarkdown::pandoc_exec()`

**Comment by atusy** [comment]
I see that the path needs be quoted for some environments.
I will fix it.
Thank you!!

cf. https://github.com/rstudio/rmarkdown/blob/947b87259333b43f47b5f59e91dc9a1ea10d1c4d/R/pandoc.R#L89

**Comment by atusy** [comment]
@JiaxiangBU Would you try the example after installing ftExtra via

```r
remotes::install_github('atusy/ftExtra/shQuote')
```

**Comment by JiaxiangBU** [comment]
Hi @atusy thanks for your reply, and fix this.

``` r
# remotes::install_github("atusy/ftExtra")
# remotes::install_github('atusy/ftExtra', ref = 'shQuote')
library(ftExtra)
```

``` r
(ftExtra_obj <-
  data.frame(
    x = c("**bold**", "*italic*"),
    y = c("^superscript^", "~subscript~"),
    z = c("***~ft~^Extra^** is*", "*Cool*"),
    stringsAsFactors = FALSE
  ) %>%
  as_flextable() %>%
  colformat_md())
```

    ## Error in knit_print.flextable(x, ...): unsupported format for flextable rendering:gfm

It works well when I reinstall ‘ftExtra’.

``` r
iris %>%
  head %>%
  as_flextable() %>%
  span_header()
```

    ## Error in knit_print.flextable(x, ...): unsupported format for flextable rendering:gfm

Works again.

``` r
library(dplyr, warn.conflicts = FALSE)
iris %>%
    group_by(Species) %>%
    slice(1:2) %>%
    as_flextable()
```

    ## Error in knit_print.flextable(x, ...): unsupported format for flextable rendering:gfm

Works again.

All examples in the README are reproducible.

``` r
class(ftExtra_obj);typeof(ftExtra_obj)
```

    ## [1] "flextable"

    ## [1] "list"

Is there a way to use this when I build it in the output type
`github_document` or `word_document`?

**Comment by atusy** [comment]
For `word_document`, it should work fine.
For `github_document`, flextable does not support the format currently.
You have to save the flextable as image by `flextable::save_as_image` and include it by `knitr::include_graphics`.

The following example works with word and html.

````
---
title: "Untitled"
output:
  word_document: null
  html_document: null
---
```{r}
library(ftExtra)
data.frame(
  x = c("**bold**", "*italic*"),
  y = c("^superscript^", "~subscript~"),
  z = c("***~ft~^Extra^** is*", "*Cool*"),
  stringsAsFactors = FALSE
) %>%
  as_flextable() %>%
  colformat_md()
```
````

**Comment by JiaxiangBU** [comment]
> The following example works with word and HTML.

Thanks, both work well for me.

**Comment by atusy** [comment]
Your welcome!
