### ISSUE TITLE
colformat_md() converts `NA` values to 'NA'

### ISSUE THREAD

**Issue by rmgpanw** [atusy/ftExtra#62]
I am using the `gtsummary` package to produce dataset summary tables, and want to apply `colformat_md` to these. `gtsummary` objects can be converted to a `flextable` objects with `gtsummary::as_flex_table()`. I can then apply `colformat_md`, however I then get unwanted 'NA' values appearing in the result:

```r
library(magrittr)
# rename mpg as BMI kg/m^2^
mtcars_bmi <- mtcars
names(mtcars_bmi)[1] <- "BMI (kg/m^2^)"

# 'NA' appears next to 'cyl'
mtcars_bmi_summary <- gtsummary::tbl_summary(mtcars_bmi[1:3]) 

mtcars_bmi_summary %>% 
  gtsummary::as_flex_table() %>% 
  ftExtra::colformat_md()
```

I can get around this by applying `colformat_md` only to columns without missing values:

```r
# specify column to format as markdown which has no `NA` values 
mtcars_bmi_summary %>% 
  gtsummary::as_flex_table() %>% 
  ftExtra::colformat_md(j = 1)
```

...or by modifying the `flextable` object, replacing `NA` values with `""`:

```r
# set `NA` values to an empty string "" in the flextable object
mtcars_bmi_summary_flextable <- mtcars_bmi_summary %>%
  gtsummary::as_flex_table() 

mtcars_bmi_summary_flextable$body$dataset <-
  mtcars_bmi_summary_flextable$body$dataset %>%
  dplyr::mutate(dplyr::across(tidyselect::everything(), ~ ifelse(is.na(.x),
                                                                 "",
                                                                 .x)))

# apply colformat_md
mtcars_bmi_summary_flextable %>% 
  ftExtra::colformat_md()
```

So there are workarounds, but would it be possible instead for `colformat_md` to be updated so it does not reformat `NA` values as 'NA'? Or perhaps there is a good reason for this behaviour that I'm unaware of. Thanks

**Comment by atusy** [comment]
Thank you for using ftExtra and for your report.
I had been thinking my implementation is enough because we can manipulate `data.frame` prior to converting to `flextable`.
Until now, I was not aware of conversion from other table building packages.

I implemented the feature in #63 and will merge soon after CI passes.
Thank you again.

**Comment by atusy** [comment]
done

**Comment by rmgpanw** [comment]
That's awesome, thanks so much!
