### ISSUE TITLE
Formatting of footnotes with markdown

### ISSUE THREAD

**Issue by s14230** [atusy/ftExtra#64]
Firstly, thank you for this amazing package 🥇 

  I'm currently trying to format the flextable footnotes to include mathematical symbols , however, I'm getting an error

`add_footer_lines(., values = as_paragraph_md( "LR $\\chi$^2^")  ) `

 I'm getting the following error 

> Error in inverse.rle(structure(list(lengths = colwidths, values = values),  : 
>   invalid 'rle' structure

 colformat_md doesn't appear to allow me to select the footer for formatting. Would appreciate any help with this, thank you,
Stephen

**Comment by atusy** [comment]
Thank you for using ftExtra, and your sponsorship!

As `values` of `flextable::add_footer_lines` only accepts character vectors,
you cannot use `as_paragraph_md`, which creates a `paragraph`-class object, directly inside it.
For now, I suggest some trick like below.

1. Add a blank footer with `flextable::add_footer_lines`
2. Format the footer with `flextable::compose`

```r
library(flextable)
library(ftExtra)
data.frame(x = 1, y = 1) %>%
  flextable() %>%
  add_footer_lines("") %>%
  compose(1, 1, as_paragraph_md("LR $\\chi$^2^"), part = "footer")
```

It may be a nice idea to request a feature on https://github.com/davidgohel/flextable so to support `add_footer_lines` to support `paragraph`- and/or `chunk`-class objects.

**Comment by s14230** [comment]
Thank you, my pleasure, it's a brilliant package as makes the formatting so easy. I'll continue to support the development. 

That solution is working great, I'll suggest it on the flextable page.
