### ISSUE TITLE
as_paragraph_md fails with an empty cell

### ISSUE THREAD

**Issue by hughjonesd** [atusy/ftExtra#67]
This relates to [huxtable#219](https://github.com/hughjonesd/huxtable/issues/219).

```r
ftExtra::as_paragraph_md("", .from = "commonmark+strikeout")
```
gives

```
Error in rep(list(flatten_branch), n) : invalid 'times' argument
```

Presumably it should just return an empty paragraph.

**Comment by atusy** [comment]
Should be fixed by now.

**Comment by atusy** [comment]
Thanks for the report
