### ISSUE TITLE
pandoc error when handling fraction 

### ISSUE THREAD

**Issue by cardiomoon** [atusy/ftExtra#69]
Hello ! 

Package "ftExtra" is very cool.  Thanks.

I have a problem to  insert fraction in flextable.

Here is reproducible example.

Best regards,

Keon-Woong Moon 

```
library(flextable)
library(ftExtra)
data.frame(math = "$\\frac{1}{2}$",
           stringsAsFactors = FALSE) %>%
  as_flextable() %>%
  colformat_md() 
```
pandoc: pandoc: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1

I have sample problem when execute simple latex example.

```
library(flextable)
library(ftExtra)
data.frame(math = "$e^{i}$",
           stringsAsFactors = FALSE) %>%
  as_flextable() %>%
  colformat_md() 
```
pandoc: pandoc: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1

**Comment by atusy** [comment]
I am closing this issue as no updaets have been made.
Feel free to re-open if the problem continues.
