### ISSUE TITLE
`colformat_md()` + R Markdown with bibliography 

### ISSUE THREAD

**Issue by ddsjoberg** [atusy/ftExtra#77]
Hello @atusy !

I ran into a strange error while using the `colformat_md()` with R markdown. When I knit a document when I used `colformat_md()` AND that markdown document includes a `bibliography:` reference in the YAML, we get an error: 

![image](https://user-images.githubusercontent.com/26774684/166744388-aecb0115-335b-410b-8111-bfd7f2caf26b.png)

I created an RStudio Cloud project to illustrate the issue. When the `bibliography:` entry is removed, the document will knit without issue.
https://rstudio.cloud/project/4003028

Do you know how to get around this issue?

Thank you!

**Comment by ddsjoberg** [comment]
Adding copy of Rmd here, but this needs a `references.bib` file to show the error. that file is in the linked RStudio Cloud project

````
---
title: "ftExtra testing"
author: "Sjoberg"
date: '2022-05-04'
output: html_document
bibliography: "`r here::here('references.bib')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
gtsummary::trial |>
  gtsummary::tbl_summary(include = age) |>
  gtsummary::as_tibble() |>
  flextable::flextable() |>
  flextable::set_header_labels(label = "**Characteristic**", stat_0 = "**N = 200**") |>
  ftExtra::colformat_md(part = "header")
```
````

**Comment by atusy** [comment]
That comes from the YAML front matter with the inline chunk.

``` yaml
bibliography: "`r here::here('references.bib')`"
```

ftExtra is referencing the front matter with `rmarkdown::metadata`, but it is recording values prior to knit.
You need to specify path as a string, not a chunk at least for now.

``` r
> rmarkdown::metadata
## $title
## [1] "ftExtra testing"
## 
## $author
## [1] "Sjoberg"
## 
## $date
## [1] "2022-05-04"
## 
## $output
## [1] "html_document"
## 
## $bibliography
## [1] "`r here::here('references.bib')`"
```

**Comment by atusy** [comment]
A workaround is to give bibligraphy via `pandoc_args`

``` yaml
output:
  html_document:
    pandoc_args:
      - "--bibliography"
      - !expr "here::here('references.bib')"
```

**Comment by ddsjoberg** [comment]
Thanks @atusy !

We keep all our projects in GitHub, so the full path may change depending on who clones a repo and where they clone it to. So that'll be an issue for me and my team for now.

Regarding the gtsummary users, I've had a few reports of people confused by the error since the release. I'm not sure the best solution is for them...something to think on for sure!

**Comment by ddsjoberg** [comment]
oh didn't see your workaround before pressing submit on the above comment! great that there is a work-around, but still need to think on messaging to users who are using the YAML in the more common way. It's too bad the pandoc error is so mysterious.

**Comment by ddsjoberg** [comment]
thanks @atusy !

do you think it's possible to make an update that would allow the use of this function with any functioning YAML? I did a small search, hoping to find a function in the rmarkdown package that would evaluate in-line code chunks, but I didn't see it. (But it must be out there somewhere, right?)

Anyway, I threw this (somewhat clunky) function together to evaluate in-ine code chunks. Could something like this (or preferably, a solution already implemented in rmarkdown) to evaluate the YAML before Pandoc returns the error? I am still trying to wrap my head around how the YAML is being used to make this function work 🤔 


``` r
eval_inline_chunk <- function(x) {
  sections_to_be_evaluated <-
    # extract everything between "`r" and "`"
    stringr::str_extract_all(x, "\\`r .*?\\`") |>
    unlist()
  
  # evaluate each inline code chunk separately
  sections_evaluated <-
    purrr::map_chr(
      sections_to_be_evaluated, 
      ~ .x |> 
        # remove the "`r" and "`"
        stringr::str_replace_all(
          pattern = "\\`r (.*?)\\`",
          replacement = ("\\1")
        ) |> 
        # evaluate string
        rlang::parse_expr() |>
        eval()
    )
  
  # replace unevaluated code with evaluated strings
  evaluated_string <- x
  for (i in seq_along(sections_to_be_evaluated)) {
    evaluated_string <-
      stringr::str_replace_all(
        evaluated_string,
        pattern = stringr::fixed(sections_to_be_evaluated[i]),
        replacement = stringr::fixed(sections_evaluated[i])
      )
  }
  evaluated_string
}

eval_inline_chunk("text '`r basename(here::here())`' print a letter `r letters[6]`")
#> [1] "text 'reprex-ccc6995e0c-girly-unau' print a letter f"
eval_inline_chunk("no code to eval")
#> [1] "no code to eval"
```

<sup>Created on 2022-05-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by atusy** [comment]
I would rather extract YAML front matter as text and then process it with `knitr::knit`.
However, this approach still needs some considerations.

- `knitr::knit` won't process `!expr`
- User-side `knitr::knit` may inherit environment fron the parent, and may result different output in **ftExtra**-side `knitr::knit`.

I would llike to take some time to consider the approach.

Let me add warning in the next release and think about more in the later release.

**Comment by ddsjoberg** [comment]
oy, this sounds tricky!

If you have recommendations for how this should be added in gtsummary, please do let me know. Because the function it used internally, a typical user won't be aware that it's even running in the background and we can't require any special instructions on their part.

**Comment by atusy** [comment]
@ddsjoberg
On #78, I decided to add the `metadata` argument to `colformat_md` and `as_paragraph_md`.
You can give alternative metadata instead of `rmarkdown::metadata`.
If you do not need bibliography, just pass `list()`.
Otherwise, you have to manually knit the YAML front matter.

``` r
tf <- tempfile(fileext = ".Rmd")
yaml::write_yaml(metadata, tf)
knitr::knit(tf)
metadata <- yaml::read_yaml(tf)

mtcars[1:2, 1:2] |>
  ftExtra::as_flextable() |>
  ftExtra::colformat_md(..., metadata = metadata)
```

**Comment by atusy** [comment]
If it  works well, then I'll merge.

**Comment by ddsjoberg** [comment]
I installed the new version on RStudio Cloud. When i knit, however, i get the same error
![image](https://user-images.githubusercontent.com/26774684/167165142-5442ba98-eb06-4db3-bb79-9fc76889f6c7.png)

**Comment by atusy** [comment]
It seems like the warning is suppressed somehow by rmarkdown.

Anyway, you need to follow the instruction above I mentioned to avoid the error. 

https://github.com/atusy/ftExtra/issues/77#issuecomment-1119716190

**Comment by atusy** [comment]
Also, if you switch to `Issues` tab, it is clear that the problem comes from the invalid path.

![image](https://user-images.githubusercontent.com/30277794/167168835-c982b515-dbf9-4203-a11c-5df87afd1ceb.png)

**Comment by ddsjoberg** [comment]
Thank you so so much for looking into this and adding the messaging!

I am going to update my personal workflow to include these updates! 

I am trying to think how I could make this work with gtsummary 🤔 If a user is not using this feature, we strip the markdown syntax from the header for them; otherwise we have `colformat_md()` to style the headers. Maybe I could wrap it up like this:
```r
tryCatch(
  colformat_md(),
  error = function(e) {
    .function_that_strips_markdown_syntax(x)
  }
)
```

But I"ll need to look into the details about when the error happens...sounds like it may not be when the function is called. Rather it's when the pandoc conversion occurs.....

**Comment by atusy** [comment]
You do not need `tryCatch`.
What you do is examine the content of `rmarkdown::metadata`, modify it, and then pass it to `colformat_md` inside the **gtsummary**.

BTW, I think I will drop warning message from the PR because

- the cause of the error can easily be found from the log of R Markdown https://github.com/atusy/ftExtra/issues/77#issuecomment-1119764585
- the warning seems to be supressed in the log https://github.com/atusy/ftExtra/issues/77#issuecomment-1119762165

**Comment by ddsjoberg** [comment]
Gotcha, thank you!
