### ISSUE TITLE
markdown footnotes generating flextable warning "Usage of empty symbol '' with footnote should not happen"

### ISSUE THREAD

**Issue by MRMHmdeleeuw** [atusy/ftExtra#84]
Hello and thank you for making the ftExtra package available. I'm using markdown formatting including footnotes in flextables thanks to ftExtra. However, for each table containing one or more (inline`^[...]`) footnotes, I get an annoying 10 sec delay during preview and markdown::render with the following warning from the flextable package

```
Usage of empty symbol '' with footnote should not happen, 
use `add_footer_lines()` instead, it does not require any symbol. 
This usage will be forbidden in the next release. Please, wait for 10 seconds!
```

Current versions of packages are 0.5.0 for ftExtra and 0.8.3 for flextable. For now, I have patched `footnote.R`'s `add_footnotes` with

```
68c68
<                       ref_symbols = rep("", n),
---
>                       ref_symbols = rep(" ", n),
```
This adds a barely visible space in front of the footnote reference in the footnote itself and gets rid of the warning. Maybe you could pick this up with @davidgohel to sort it out? Thanks again and best regards.

**Comment by davidgohel** [comment]
Sorry for that @atusy, I did not detect you were using `add_footnotes()` with some empty ref. This is there: https://github.com/davidgohel/flextable/blob/bf3bae77279f9088a691984e1ba27934219adfd2/R/footnote.R#L90

Could you use `add_footer_lines()` instead? Let me know if you need help or more details.

**Comment by atusy** [comment]
Thanks a lot for both of you.

I will try make sometime this weekend :)

**Comment by atusy** [comment]
@MRMHmdeleeuw I have opened PR #85 to fix the problem. Would you try it? Below is the way to install the PR version.

``` r
install.packages("remotes")
remotes::install_github("atusy/ftExtra#85")
```

**Comment by atusy** [comment]
I merged the PR, so you can try with `remotes::install_github("atusy/ftExtra")` as well.
Let me know if you find any problems.
Maybe I release ftExtra on CRAN this week.

**Comment by MRMHmdeleeuw** [comment]
Hello @atushy, I did the `remotes::install_github("atusy/ftExtra")` replacing my patch and reknitted a few Rmd files targeting MS Word with footnotes in flextables. No warniings/delays anymore, so thank you for the quick fix.
