### ISSUE TITLE
Registered S3 method overwritten by 'ftExtra':

### ISSUE THREAD

**Issue by Generalized** [atusy/ftExtra#92]
Dear Author,
I'm using ftExtra with flextable to enable subscripts directly from the content (rather than post-factum composing/updating cells).
Got a warning and just wanted to make sure if it's risky.

> ## Registered S3 method overwritten by 'ftExtra':
> ##   method                  from     
> ##   as_flextable.data.frame flextable

I don't load the package via library, using it directly.
It happens even with the simplest mtcars example (no markdown, but triggers the warning):
```{r}
mtcars %>% 
flextable() %>% 
ftExtra::colformat_md(j = 2, part = "body") 
```

Funny, I'm getting it only from RMarkdown. I don't see it in the console, when running it manually:
![obraz](https://github.com/atusy/ftExtra/assets/60151643/500443b7-96a2-4be3-bc7a-50c5bbef533f)

![obraz](https://github.com/atusy/ftExtra/assets/60151643/3ca00669-d144-4936-b7b0-143f7333cd5d)

**Comment by atusy** [comment]
Ah hah!
It seems **ftExtra** and **flextable** have functions with the same name...
Well, only **ftExtra** had that function in the past...

I would deprecate `ftExtra:::as_flextable.data.frame` and defunct in the future versions.

For now, you can suppress the message by chunk option in R Markdown.

````
```{r, message=FALSE}
mtcars %>% 
flextable() %>% 
ftExtra::colformat_md(j = 2, part = "body") 
```
````

**Comment by atusy** [comment]
I opened a PR to deprecate masking functions.
In the future release, I will remove them.
