### ISSUE TITLE
is it possible to get a vector of row heights?

### ISSUE THREAD

**Issue by jic007** [atusy/ftExtra#93]
is it possible to get a vector of row heights? Given that I have some columns with long text that the text gets wrapped. I need to have this piece of information so that I know how to split tables that fit in a powerpoint slide

**Comment by atusy** [comment]
I do not think so...
At least **ftExtra** does not offer such a feature.
Maybe you would better look into **flextable** if such a feature is natively available.

**Comment by atusy** [comment]
let me close the issue, and consider visiting flextable.
make sure you follow the issue guide.

```
**Not a bug or feature request? If you are looking for help on how to use the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**  
```
